DROP PROCEDURE IF EXISTS CASELLO_TRAFFICATO;
DELIMITER &&
CREATE PROCEDURE CASELLO_TRAFFICATO(
    OUT Out_somma INT,
    OUT Out_max_id INT
)
MODIFIES SQL DATA
BEGIN
    SELECT C.Id, COUNT(*) AS NUMERO_VOLTE
    INTO Out_max_id, Out_somma
    FROM (TRAGITTI T JOIN CASELLI C ON T.Casello_Ingresso = C.Id)
    GROUP BY C.Id
    ORDER BY NUMERO_VOLTE DESC
    LIMIT 1;
END &&
DELIMITER ;
